extends:
   - 'airbnb-base'
env:
  node: true
  browser: true
parser: "babel-eslint"
parserOptions: 
  ecmaVersion: 6
  sourceType: 'script'
  modules: 0
rules:
  no-console: 0
  no-debugger: 1
  no-unused-vars: 0
  strict: 0
  linebreak-style: 0
  no-underscore-dangle: 0
  no-empty: 0
  max-len: 0
  eol-last: 0
  no-undef: 0
  indent:
    - 2    
    - 2    
    - ignoredNodes: 
        - "ConditionalExpression"    
      SwitchCase: 1      
  no-param-reassign:
    - 2
    - props: false
  operator-linebreak:
    - 2
    - "after"
  no-plusplus:
    - 0
  nonblock-statement-body-position:
    - 2
    - "below"
  curly: 
    - 2
    - "multi-or-nest"
  camelcase: 
    - 0
    - properties: 'never'  
    #- ingoreDestructuring: true
  quotes: 
    - 2
    - "double"